name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  generic:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test
  wasm:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: jetli/wasm-pack-action@v0.4.0
    - name: Run tests
      run: wasm-pack test --node